version: 2
jobs:
  build:
    docker:
    - image: jdrouet/docker-with-buildx:stable
    steps:
      - checkout
      - run:
          name: "Setup custom environment variables"
          command: echo 'export MY_ENV_VAR="FOO"' >> $BASH_ENV
      - run: # print the name of the branch we're on
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
      # Run another step, the same as above; note that you can
      # invoke environment variable without curly braces.
      - run:
          name: "What branch am I on now?"
          command: echo $CIRCLE_BRANCH
      - run:
          name: "What was my custom environment variable?"
          command: echo ${MY_ENV_VAR}
      - run:
          name: "Print an env var stored in the Project"
          command: echo ${PROJECT_ENV_VAR}
      - run:
          name: "Print an env var stored in a Context"
          command: echo ${CONTEXT_ENV_VAR}
    #   - run:
    #       name: "List dir"
    #       command: ls -l
    #   - run: 
    #       name: "Read version from VERSION file"
    #       command: echo 'export MY_VERSION="1.0.0"' >> $BASH_ENV
    #   - run: 
    #       name: "Print version"
    #       command: echo ${MY_VERSION}
    #     - run: 
    #       name: "Print version 2"
    #       command: echo $MY_VERSION
    #   - run: 
    #       name: "Print BASH_ENV"
    #       command: echo ${BASH_ENV}
      - setup_remote_docker:
          version: 18.09.3
      - run: 
          name: "Docker login"
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
      - run: 
          name: "Docker build & push, with buildx"
          command: docker buildx build --platform linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/i386,linux/amd64 -t zmad5306/video-converter:latest -t zmad5306/video-converter:${MY_VERSION} --push .
workflows: # a single workflow with a single job called build
  build:
    jobs:
      - build:
          context: Testing-Env-Vars