version: 2.1
jobs:
  build:
    docker:
    - image: jdrouet/docker-with-buildx:stable
    steps:
     - checkout
     - setup_remote_docker:
        version: 18.09.3
     - run: 
         name: "Docker build"
         command: docker buildx build --platform linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/i386,linux/amd64 .
  build_and_publish:
    docker:
    - image: jdrouet/docker-with-buildx:stable
    steps:
     - checkout
     - setup_remote_docker:
        version: 18.09.3
     - run: 
         name: "Docker login"
         command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
     - run: 
         name: "Docker build and push"
         command: docker buildx build --platform linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/i386,linux/amd64 -t zmad5306/video-converter:latest -t zmad5306/video-converter:$(cat VERSION) --push .
workflows:
  version: 2
  build_workflow:
    jobs:
    - build_and_publish:
        filters:
          branches:
            only:
            - main
    - build:
        filters:
          branches:
            ignore:
            - main
        