version: 2
jobs:
  build:
    docker:
    - image: jdrouet/docker-with-buildx:stable
    - environment: MY_VERSION: 1.0.0
    steps:
      - checkout
      - run:
          name: "List dir"
          command: ls -l
      - run: 
          name: "Read version from VERSION file"
          command: echo 'export MY_VERSION="1.0.0"' >> $BASH_ENV
      - run: 
          name: "Print version"
          command: echo ${MY_VERSION}
        - run: 
          name: "Print version 2"
          command: echo $MY_VERSION
      - run: 
          name: "Print BASH_ENV"
          command: echo ${BASH_ENV}
      - setup_remote_docker:
          version: 18.09.3
      - run: 
          name: "Docker login"
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
      - run: 
          name: "Docker build & push, with buildx"
          command: docker buildx build --platform linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/i386,linux/amd64 -t zmad5306/video-converter:latest -t zmad5306/video-converter:${MY_VERSION} --push .
